default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

  # adapter: postgresql
  # database: app_postgres_development
  # host: localhost
  # port: 5433
  # username: apptest
  # password: password1

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

  # adapter: postgresql
  # database: app_postgres_test

production:
  <<: *default
  adapter: postgresql
  database: app_postgres_production
  username: app_postgres
  password: <%= ENV['APP_POSTGRES_DATABASE_PASSWORD'] %>
  # DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
